"""Scripted full 5-set match replayed through MatchEngine.

The match script:
  set 1: HOME 25-20            (HOME serves first, HOME on the left)
  set 2: AWAY 27-25            (through 24-24; must NOT end at 25-24)
  set 3: HOME 25-23
  set 4: AWAY 25-18
  set 5: HOME 15-12            (deciding set, target 15, mid-set side switch)
Final: HOME wins the match 3-2.

Every rally is generated by `rally()` which serves with the engine's
expected server, receives with an opposing back-row player, and finishes
the rally deterministically in one of four styles (ace, opponent attack
error, dig-loop kill, manual rally point).  After every rally we assert
scores, serve possession and the side-out rotation invariant, and that
no event of the scripted (legal) rally produced a warning.
"""
from __future__ import annotations

from core import rules
from core.engine import MatchEngine, Phase
from core.events import (AttackEvent, DigEvent, LiberoSwapEvent,
                         RallyPointEvent, ReceptionEvent, ServeEvent,
                         SetStartEvent, SubstitutionEvent)
from core.models import AWAY, HOME, MatchConfig, Player, Rating, Role, Team, other
from core.rotation import rotate_clockwise

# --------------------------------------------------------------------- teams


def build_team(prefix: str, name: str, color: str) -> Team:
    """12 players with deterministic ids '<prefix>1'..'<prefix>12'.
    Players 1-6 start, 7-11 are bench, 12 is the libero."""
    roles = [Role.SETTER, Role.OUTSIDE, Role.MIDDLE, Role.OUTSIDE,
             Role.MIDDLE, Role.OPPOSITE,
             Role.UNIVERSAL, Role.UNIVERSAL, Role.UNIVERSAL,
             Role.UNIVERSAL, Role.UNIVERSAL, Role.LIBERO]
    players = [Player(number=i + 1, name=f"{prefix}{i + 1}", role=roles[i],
                      id=f"{prefix}{i + 1}")
               for i in range(12)]
    return Team(name=name, players=players, color=color)


def build_teams() -> dict:
    return {HOME: build_team("H", "Home Hawks", "#2e7d32"),
            AWAY: build_team("A", "Away Owls", "#c62828")}


def starters(team: Team) -> list[str]:
    return [p.id for p in team.players[:6]]


def libero_of(team: Team) -> str:
    return team.players[11].id


def first_set_start(engine: MatchEngine) -> SetStartEvent:
    return SetStartEvent(
        set_number=1,
        lineups={tk: starters(engine.teams[tk]) for tk in (HOME, AWAY)},
        liberos={tk: [libero_of(engine.teams[tk])] for tk in (HOME, AWAY)},
        serving_team=HOME,
        left_team=HOME,
    )


# ------------------------------------------------------------------- helpers


def _append_clean(engine: MatchEngine, event) -> None:
    """Append an event that the script considers fully legal."""
    warnings = engine.append(event)
    assert warnings == [], f"unexpected warnings for {event!r}: {warnings}"


def rally(engine: MatchEngine, winner: str, style: int = 0) -> None:
    """Play one deterministic rally that `winner` wins, then assert the
    engine's bookkeeping: +1 point for the winner only, serve possession
    to the winner, and clockwise rotation for the winner if and only if
    the winner was receiving (side-out).  The loser never rotates."""
    st = engine.state
    srv = st.serving_team
    rcv = other(srv)
    before = {tk: list(st.team[tk].lineup) for tk in (HOME, AWAY)}
    score_before = dict(st.scores)

    server = engine.expected_server()
    assert server == before[srv][0], "expected_server must be P1 of the servers"

    def pid(team_key: str, idx: int) -> str:
        return engine.state.team[team_key].lineup[idx]

    style %= 4
    if winner == srv:
        if style == 0:                                   # ace
            _append_clean(engine, ServeEvent(
                team=srv, player_id=server, rating=Rating.PERFECT,
                trajectory=(-10.2, 7.5, 6.0, 2.0)))
        elif style == 1:                                 # receivers attack out
            _append_clean(engine, ServeEvent(
                team=srv, player_id=server, rating=Rating.GOOD))
            _append_clean(engine, ReceptionEvent(
                team=rcv, player_id=pid(rcv, 5), rating=Rating.GOOD))
            _append_clean(engine, AttackEvent(
                team=rcv, player_id=pid(rcv, 3), rating=Rating.ERROR))
        elif style == 2:                                 # dig loop, counter-kill
            _append_clean(engine, ServeEvent(
                team=srv, player_id=server, rating=Rating.GOOD))
            _append_clean(engine, ReceptionEvent(
                team=rcv, player_id=pid(rcv, 5), rating=Rating.GOOD))
            _append_clean(engine, AttackEvent(
                team=rcv, player_id=pid(rcv, 3), rating=Rating.GOOD,
                trajectory=(2.5, 1.5, -6.0, 7.0)))
            _append_clean(engine, DigEvent(
                team=srv, player_id=pid(srv, 4), rating=Rating.GOOD))
            _append_clean(engine, AttackEvent(
                team=srv, player_id=pid(srv, 2), rating=Rating.PERFECT))
        else:                                            # manual rally point
            _append_clean(engine, ServeEvent(
                team=srv, player_id=server, rating=Rating.GOOD))
            _append_clean(engine, ReceptionEvent(
                team=rcv, player_id=pid(rcv, 5), rating=Rating.POOR))
            _append_clean(engine, RallyPointEvent(team=srv, reason="net fault"))
    else:
        if style == 0:                                   # service error
            _append_clean(engine, ServeEvent(
                team=srv, player_id=server, rating=Rating.ERROR))
        elif style == 1:                                 # clean kill
            _append_clean(engine, ServeEvent(
                team=srv, player_id=server, rating=Rating.GOOD))
            _append_clean(engine, ReceptionEvent(
                team=rcv, player_id=pid(rcv, 5), rating=Rating.PERFECT))
            _append_clean(engine, AttackEvent(
                team=rcv, player_id=pid(rcv, 3), rating=Rating.PERFECT,
                trajectory=(1.0, 2.0, -8.0, 8.5)))
        elif style == 2:                                 # long dig loop, kill
            _append_clean(engine, ServeEvent(
                team=srv, player_id=server, rating=Rating.GOOD))
            _append_clean(engine, ReceptionEvent(
                team=rcv, player_id=pid(rcv, 5), rating=Rating.GOOD))
            _append_clean(engine, AttackEvent(
                team=rcv, player_id=pid(rcv, 3), rating=Rating.GOOD))
            _append_clean(engine, DigEvent(
                team=srv, player_id=pid(srv, 4), rating=Rating.GOOD))
            _append_clean(engine, AttackEvent(
                team=srv, player_id=pid(srv, 2), rating=Rating.GOOD))
            _append_clean(engine, DigEvent(
                team=rcv, player_id=pid(rcv, 4), rating=Rating.GOOD))
            _append_clean(engine, AttackEvent(
                team=rcv, player_id=pid(rcv, 1), rating=Rating.PERFECT))
        else:                                            # manual rally point
            _append_clean(engine, ServeEvent(
                team=srv, player_id=server, rating=Rating.GOOD))
            _append_clean(engine, ReceptionEvent(
                team=rcv, player_id=pid(rcv, 5), rating=Rating.GOOD))
            _append_clean(engine, AttackEvent(
                team=rcv, player_id=pid(rcv, 3), rating=Rating.GOOD))
            _append_clean(engine, DigEvent(
                team=srv, player_id=pid(srv, 4), rating=Rating.GOOD))
            _append_clean(engine, RallyPointEvent(
                team=rcv, reason="ball handling fault"))

    st = engine.state
    loser = other(winner)
    assert st.scores[winner] == score_before[winner] + 1, "winner gets one point"
    assert st.scores[loser] == score_before[loser], "loser score unchanged"
    assert st.serving_team == winner, "rally winner serves next"
    if winner == srv:
        assert st.team[winner].lineup == before[winner], \
            "no rotation when winning on own serve"
    else:
        assert st.team[winner].lineup == rotate_clockwise(before[winner]), \
            "side-out: receiving winner rotates exactly one position clockwise"
    assert st.team[loser].lineup == before[loser], "loser never rotates"
    assert st.phase in (Phase.AWAIT_SERVE, Phase.SET_OVER, Phase.MATCH_OVER)


def play_set(engine: MatchEngine, winners: list[str], hooks: dict | None = None) -> None:
    """Play rallies for `winners`; hooks[i] runs before rally i (subs etc.)."""
    for i, w in enumerate(winners):
        if hooks and i in hooks:
            hooks[i](engine)
        rally(engine, w, style=i)


def do_substitution(engine: MatchEngine, team_key: str, player_in: str) -> None:
    ts = engine.state.team[team_key]
    subs_before = ts.subs_used
    player_out = ts.lineup[2]
    expected = list(ts.lineup)
    expected[2] = player_in
    _append_clean(engine, SubstitutionEvent(
        team=team_key, player_out=player_out, player_in=player_in))
    assert engine.state.team[team_key].lineup == expected
    assert engine.state.team[team_key].subs_used == subs_before + 1


def libero_in(engine: MatchEngine, team_key: str) -> str:
    """Libero enters for the current P6 (back row). Returns the partner id."""
    lib = libero_of(engine.teams[team_key])
    partner = engine.state.team[team_key].lineup[5]
    _append_clean(engine, LiberoSwapEvent(
        team=team_key, libero_id=lib, partner_id=partner))
    assert engine.state.team[team_key].lineup[5] == lib
    assert engine.state.team[team_key].libero_replaced[lib] == partner
    return partner


def libero_out(engine: MatchEngine, team_key: str, partner: str) -> None:
    lib = libero_of(engine.teams[team_key])
    lineup = engine.state.team[team_key].lineup
    slot = lineup.index(lib)
    _append_clean(engine, LiberoSwapEvent(
        team=team_key, libero_id=lib, partner_id=partner))
    assert engine.state.team[team_key].lineup[slot] == partner
    assert lib not in engine.state.team[team_key].lineup
    assert lib not in engine.state.team[team_key].libero_replaced


def advance_set(engine: MatchEngine, expect_number: int,
                expect_serving: str, expect_left: str) -> None:
    """Use the engine's own suggestion between sets and verify the
    alternation of first serve and playing sides."""
    prev_left = engine.state.left_team if not engine.state.switched_mid_set \
        else other(engine.state.left_team)
    prev_first = engine.state.set_first_server
    sug = engine.suggest_next_set_start()
    assert sug is not None
    assert sug.set_number == expect_number
    assert sug.serving_team == expect_serving == other(prev_first), \
        "first serve alternates between sets"
    assert sug.left_team == expect_left, "sides alternate between sets"
    # suggested lineups are the previous starting lineups (subs and libero
    # exchanges undone)
    for tk in (HOME, AWAY):
        assert sug.lineups[tk] == engine.state.team[tk].starting_lineup
        assert libero_of(engine.teams[tk]) not in sug.lineups[tk]
    _append_clean(engine, sug)
    assert engine.state.phase == Phase.AWAIT_SERVE
    assert engine.state.scores == {HOME: 0, AWAY: 0}
    assert engine.state.set_number == expect_number
    assert engine.state.serving_team == expect_serving
    assert engine.state.left_team == expect_left


# ---------------------------------------------------------------- the match


def test_full_five_set_match():
    teams = build_teams()
    engine = MatchEngine(MatchConfig(), teams)
    assert engine.state.phase == Phase.BEFORE_SET

    # ------------------------------------------------ set 1: HOME 25-20
    _append_clean(engine, first_set_start(engine))
    assert engine.state.phase == Phase.AWAIT_SERVE
    assert engine.state.serving_team == HOME
    assert engine.state.left_team == HOME
    assert rules.set_target(engine.config, 1) == 25

    partners: dict[str, str] = {}
    hooks1 = {
        # HOME substitution mid-set (bench player H7 for the current P3)
        6: lambda e: do_substitution(e, HOME, "H7"),
        # HOME libero in for P6 while HOME is receiving, out one rally later
        10: lambda e: partners.__setitem__(HOME, libero_in(e, HOME)),
        11: lambda e: libero_out(e, HOME, partners[HOME]),
        # AWAY libero exchange
        13: lambda e: partners.__setitem__(AWAY, libero_in(e, AWAY)),
        14: lambda e: libero_out(e, AWAY, partners[AWAY]),
    }
    play_set(engine, [HOME, AWAY] * 20 + [HOME] * 5, hooks1)
    assert engine.state.scores == {HOME: 25, AWAY: 20}
    assert engine.state.phase == Phase.SET_OVER
    assert engine.state.set_scores == {HOME: 1, AWAY: 0}
    assert engine.state.last_set_winner == HOME

    # ------------------------------------------------ set 2: AWAY 27-25
    advance_set(engine, 2, expect_serving=AWAY, expect_left=AWAY)
    hooks2 = {2: lambda e: do_substitution(e, AWAY, "A7")}
    play_set(engine, [AWAY, HOME] * 24, hooks2)          # -> 24-24
    assert engine.state.scores == {HOME: 24, AWAY: 24}
    assert engine.state.phase == Phase.AWAIT_SERVE, "24-24: set continues"

    rally(engine, AWAY, style=48)                        # 25-24 AWAY
    assert engine.state.scores == {HOME: 24, AWAY: 25}
    assert engine.state.phase == Phase.AWAIT_SERVE, \
        "set must NOT end at 25-24 (2-point lead required)"
    assert engine.state.set_scores == {HOME: 1, AWAY: 0}

    rally(engine, HOME, style=49)                        # 25-25
    rally(engine, AWAY, style=50)                        # 26-25
    assert engine.state.phase == Phase.AWAIT_SERVE, "26-25 is only a 1-point lead"
    rally(engine, AWAY, style=51)                        # 27-25, set over
    assert engine.state.scores == {HOME: 25, AWAY: 27}
    assert engine.state.phase == Phase.SET_OVER
    assert engine.state.set_scores == {HOME: 1, AWAY: 1}
    assert engine.state.last_set_winner == AWAY

    # ------------------------------------------------ set 3: HOME 25-23
    advance_set(engine, 3, expect_serving=HOME, expect_left=HOME)
    play_set(engine, [HOME, AWAY] * 23 + [HOME] * 2)
    assert engine.state.scores == {HOME: 25, AWAY: 23}
    assert engine.state.set_scores == {HOME: 2, AWAY: 1}

    # ------------------------------------------------ set 4: AWAY 25-18
    advance_set(engine, 4, expect_serving=AWAY, expect_left=AWAY)
    play_set(engine, [AWAY, HOME] * 18 + [AWAY] * 7)
    assert engine.state.scores == {HOME: 18, AWAY: 25}
    assert engine.state.set_scores == {HOME: 2, AWAY: 2}

    # ------------------------------ set 5 (deciding): HOME 15-12, switch at 8
    advance_set(engine, 5, expect_serving=HOME, expect_left=HOME)
    assert rules.is_deciding_set(engine.config, 5)
    assert rules.set_target(engine.config, 5) == 15, "deciding set targets 15"

    winners5 = [HOME, AWAY] * 12 + [HOME] * 3
    flips = []
    for i, w in enumerate(winners5):
        left_before = engine.state.left_team
        rally(engine, w, style=i)
        if engine.state.left_team != left_before:
            flips.append((left_before, engine.state.left_team,
                          dict(engine.state.scores)))
    assert len(flips) == 1, "sides switch exactly once in the deciding set"
    assert flips[0][2] == {HOME: 8, AWAY: 7}, \
        "the switch happens when the leading team reaches 8"
    assert flips[0][0] == HOME and flips[0][1] == AWAY
    assert engine.state.left_team == AWAY

    # ------------------------------------------------ final state
    assert engine.state.scores == {HOME: 15, AWAY: 12}
    assert engine.state.phase == Phase.MATCH_OVER
    assert engine.state.set_scores == {HOME: 3, AWAY: 2}
    assert engine.state.last_set_winner == HOME
    assert engine.suggest_next_set_start() is None, "no set 6 after match over"

    # ------------------------------------- determinism: replay from scratch
    fresh = MatchEngine(MatchConfig(), build_teams())
    fresh.load_events(list(engine.events))
    assert len(fresh.events) == len(engine.events)
    assert fresh.state.phase == Phase.MATCH_OVER
    assert fresh.state.scores == engine.state.scores
    assert fresh.state.set_scores == engine.state.set_scores
    assert fresh.state.serving_team == engine.state.serving_team
    assert fresh.state.left_team == engine.state.left_team
    assert fresh.state.set_number == engine.state.set_number
    for tk in (HOME, AWAY):
        assert fresh.state.team[tk] == engine.state.team[tk]
    assert fresh.state == engine.state, "replay is fully deterministic"


# ------------------------------------------- intentional-warning spot checks


def test_wrong_server_and_wrong_team_warn():
    engine = MatchEngine(MatchConfig(), build_teams())
    _append_clean(engine, first_set_start(engine))

    # serve by the P2 player instead of P1 -> warning, but event applied
    wrong = engine.state.team[HOME].lineup[1]
    warnings = engine.append(ServeEvent(team=HOME, player_id=wrong,
                                        rating=Rating.PERFECT))
    assert any("expected server" in w for w in warnings)
    assert engine.state.scores == {HOME: 1, AWAY: 0}, "event applied anyway"

    # serve by the team without possession -> warning
    server = engine.state.team[AWAY].lineup[0]
    warnings = engine.append(ServeEvent(team=AWAY, player_id=server,
                                        rating=Rating.PERFECT))
    assert any("serve possession" in w for w in warnings)
