/** Golden-fixture conformance suite: the TypeScript engine must reproduce
 * the Python reference engine EXACTLY.
 *
 * Fixtures in tablet/conformance/ are generated by tools/gen_conformance.py
 * from the real core.engine.MatchEngine: for every event they record the
 * serialized event, the warnings append() returned, and a full state
 * snapshot — plus final stats and normalized trajectories. This suite is
 * the release-sync contract: regenerate the fixtures after every Python
 * core/ change and this file must stay green (see tablet/RELEASING.md).
 */
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { MatchEngine } from "../src/core/engine";
import { event_from_dict, event_to_dict } from "../src/core/events";
import {
  TEAM_KEYS, TeamKey, config_from_dict, team_from_dict,
} from "../src/core/models";
import { TeamStats, compute_stats } from "../src/core/stats";
import { collect_trajectories } from "../src/core/trajectories";

const DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "conformance");

/** Mirror of snapshot() in tools/gen_conformance.py. */
function snapshot(engine: MatchEngine) {
  const st = engine.state;
  const team: Record<string, unknown> = {};
  for (const tk of TEAM_KEYS) {
    const ts = st.team[tk];
    team[tk] = {
      lineup: [...ts.lineup],
      starting_lineup: [...ts.starting_lineup],
      liberos: [...ts.liberos],
      subs_used: ts.subs_used,
      sub_pairs: ts.sub_pairs.map((p) => [...p]),
      libero_replaced: { ...ts.libero_replaced },
      timeouts: ts.timeouts,
    };
  }
  const sug = engine.suggest_next_set_start();
  return {
    phase: st.phase,
    set_number: st.set_number,
    scores: { ...st.scores },
    set_scores: { ...st.set_scores },
    serving_team: st.serving_team,
    set_first_server: st.set_first_server,
    left_team: st.left_team,
    switched_mid_set: st.switched_mid_set,
    attacking_team: st.attacking_team,
    last_set_winner: st.last_set_winner,
    team,
    expected_server: engine.expected_server(),
    rally_live: engine.rally_live(),
    set_point_info: engine.set_point_info(),
    pending_alerts: engine.pending_alerts(),
    suggest_next: sug === null ? null : event_to_dict(sug),
  };
}

/** Mirror of stats_to_dict() in tools/gen_conformance.py. */
function stats_to_dict(stats: Record<TeamKey, TeamStats>) {
  const out: Record<string, unknown> = {};
  for (const tk of TEAM_KEYS) {
    const ts = stats[tk];
    const players: Record<string, unknown> = {};
    for (const [pid, ps] of Object.entries(ts.players)) {
      const skills: Record<string, unknown> = {};
      for (const [skill, line] of Object.entries(ps.skills)) {
        skills[skill] = { ...line.counts };
      }
      players[pid] = skills;
    }
    const totals: Record<string, unknown> = {};
    for (const [skill, line] of Object.entries(ts.totals)) {
      totals[skill] = { ...line.counts };
    }
    out[tk] = { players, totals, points_breakdown: { ...ts.points_breakdown } };
  }
  return out;
}

const files = readdirSync(DIR).filter((f) => f.endsWith(".json")).sort();

describe.each(files)("conformance %s", (file) => {
  const fx = JSON.parse(readFileSync(join(DIR, file), "utf-8"));
  const config = config_from_dict(fx.config);
  const teams = {
    home: team_from_dict(fx.teams.home),
    away: team_from_dict(fx.teams.away),
  };

  it("replays every event to the exact Python state and warnings", () => {
    const engine = new MatchEngine(config, teams);
    fx.steps.forEach((step: any, i: number) => {
      const e = event_from_dict(step.event);
      // serialization round-trip reproduces the Python dict exactly
      expect(event_to_dict(e), `event round-trip @${i}`).toEqual(step.event);
      const warnings = engine.append(e);
      expect(warnings, `warnings @${i}`).toEqual(step.warnings);
      expect(snapshot(engine), `state @${i}`).toEqual(step.state);
    });
  });

  it("undo walks back through the recorded snapshots", () => {
    const engine = new MatchEngine(config, teams);
    engine.load_events(fx.steps.map((s: any) => event_from_dict(s.event)));
    const n = fx.steps.length;
    for (let k = 1; k <= Math.min(20, n); k++) {
      expect(engine.undo()).not.toBeNull();
      const idx = n - 1 - k;
      if (idx >= 0) {
        expect(snapshot(engine), `undo to @${idx}`)
          .toEqual(fx.steps[idx].state);
      }
    }
  });

  it("reproduces final stats and trajectories", () => {
    const events = fx.steps.map((s: any) => event_from_dict(s.event));
    expect(stats_to_dict(compute_stats(events, teams)))
      .toEqual(fx.final_stats);
    const trajs = collect_trajectories(config, teams, events)
      .map((t) => ({
        team: t.team, player_id: t.player_id, skill: t.skill,
        rating: t.rating, set_number: t.set_number, line: [...t.line],
      }));
    expect(trajs).toEqual(fx.final_trajectories);
  });
});
